name: Fetch Encrypted Secrets

on:
  workflow_call:
    inputs:
      uuid:
        required: true
        type: string
      secrets_base64:
        required: true
        type: string

jobs:
  download-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Decode secrets
        shell: python
        run: |
          import base64
          
          secrets_base64 = '${{ inputs.secrets_base64 }}'
          decoded_content = base64.b64decode(secrets_base64)
          
          with open('secrets.zip', 'wb') as f:
              f.write(decoded_content)

      - name: Upload Encrypted Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-zip
          path: secrets.zip
          retention-days: 1
